# Generated by Django 5.2.3 on 2025-07-20 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praevia_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditchecklistitem',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='praevia_app.audit'),
        ),
        migrations.AddField(
            model_name='contentieux',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='contentieux_actions', to='praevia_app.action'),
        ),
        migrations.AddField(
            model_name='document',
            name='contentieux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='praevia_app.contentieux'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentieux',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='contentieux_documents', to='praevia_app.document'),
        ),
        migrations.AddField(
            model_name='dossieratmp',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossieratmp',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='dossier_atmp_documents', to='praevia_app.document'),
        ),
        migrations.AddField(
            model_name='dossieratmp',
            name='safety_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentieux',
            name='dossier_atmp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contentieux', to='praevia_app.dossieratmp'),
        ),
        migrations.AddField(
            model_name='audit',
            name='dossier_atmp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='praevia_app.dossieratmp'),
        ),
        migrations.AddField(
            model_name='juridictionstep',
            name='contentieux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridiction_steps_set', to='praevia_app.contentieux'),
        ),
        migrations.AddField(
            model_name='temoin',
            name='dossier_atmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoin_set', to='praevia_app.dossieratmp'),
        ),
        migrations.AddField(
            model_name='tiers',
            name='dossier_atmp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='praevia_app.dossieratmp'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='contentieux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_set', to='praevia_app.contentieux'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
