# Generated by Django 5.2.3 on 2025-07-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praevia_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossieratmp',
            name='accident',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='entreprise',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='salarie',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='temoins',
            field=models.JSONField(default=list),
        ),
    ]
