# Generated by Django 5.2.3 on 2025-07-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praevia_app', '0003_alter_dossieratmp_accident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossieratmp',
            name='accident',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='entreprise',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='salarie',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='temoins',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
