# Generated by Django 5.2.3 on 2025-07-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praevia_app', '0004_alter_dossieratmp_accident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossieratmp',
            name='temoins',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
