# Generated by Django 5.2.3 on 2025-07-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praevia_app', '0005_remove_dossieratmp_temoins_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentieux',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
