# Generated by Django 5.2.3 on 2025-07-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praevia_app', '0006_alter_contentieux_reference_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentieux',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('EN_COURS', 'En Cours'), ('CLOTURE', 'Clôturé')], default='DRAFT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DAT', 'DAT'), ('CERTIFICAT_MEDICAL', 'Certificat Médical'), ('ARRET_TRAVAIL', 'Arrêt de Travail'), ('TEMOIGNAGE', 'Témoignage'), ('DECISION_CPAM', 'Décision CPAM'), ('EXPERTISE_MEDICALE', 'Expertise Médicale'), ('LETTRE_RESERVE', 'Lettre de Réserve'), ('CONTRAT_TRAVAIL', 'Contrat de Travail'), ('FICHE_POSTE', 'Fiche de Poste'), ('RAPPORT_ENQUETE', 'Rapport d’Enquête'), ('NOTIFICATION_TAUX', 'Notification de Taux'), ('COURRIER', 'Courrier'), ('AUTRE', 'Autre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juridictionstep',
            name='juridiction',
            field=models.CharField(blank=True, choices=[('TRIBUNAL_JUDICIAIRE', 'Tribunal Judiciaire'), ('COUR_APPEL', "Cour d'Appel"), ('COUR_CASSATION', 'Cour de Cassation')], max_length=50, null=True),
        ),
    ]
