# Generated by Django 5.2.3 on 2025-07-22 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praevia_app', '0007_alter_contentieux_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossieratmp',
            name='safety_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_dossiers', to=settings.AUTH_USER_MODEL),
        ),
    ]
