# Generated by Django 5.2.3 on 2025-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('JURISTE', 'Jurist'), ('RH', 'Resources Humaines'), ('MANAGER', 'Manager'), ('SAFETY_MANAGER', 'Safety Manager'), ('QS', 'Quality, Safety, Environment'), ('DR', 'Direction'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='Defines the user role in the system', max_length=20, verbose_name='Role'),
        ),
    ]
