# Generated by Django 5.2.3 on 2025-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seeded',
            field=models.BooleanField(default=False, help_text='Indicates if this user was created by a seeding script'),
        ),
    ]
